FROM node:20-alpine3.17 AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . ./

ARG PUBLIC_URL
ENV PUBLIC_URL=$PUBLIC_URL

RUN yarn build

# Etapa final com serve
FROM node:20-alpine3.17

WORKDIR /app
RUN yarn global add serve

COPY --from=builder /app/build ./build

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
