FROM node:16.20.2-alpine3.14 as builder

WORKDIR /app/frontend

COPY package.json ./

RUN yarn

COPY . ./

ARG PUBLIC_URL

RUN yarn build --base=/mudar-aqui/

FROM nginx:1.23.1

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/frontend/build/ /var/www/
